name: headless_button
description: Headless Button component package.
version: 1.0.0
homepage: https://github.com/777genius/flutter_headless
repository: https://github.com/777genius/flutter_headless
issue_tracker: https://github.com/777genius/flutter_headless/issues

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  headless_foundation:
    version: ^1.0.0
  headless_contracts:
    version: ^1.0.0
  headless_theme:
    version: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  headless_test:
    version: ^1.0.0
  lints: ^5.1.1
