include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Const
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_declarations: true

    # Widgets
    avoid_unnecessary_containers: true
    use_key_in_widget_constructors: true

    # Style
    prefer_single_quotes: true
    always_use_package_imports: true
    sort_child_properties_last: true

    # Safety
    avoid_print: true
    avoid_dynamic_calls: true

    # Documentation
    public_member_api_docs: true
