name: headless_contracts
description: Renderer contracts and slot overrides for Headless components.
version: 1.1.0
homepage: https://github.com/777genius/flutter_headless
repository: https://github.com/777genius/flutter_headless
issue_tracker: https://github.com/777genius/flutter_headless/issues

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.16.0
  headless_foundation:
    version: ^1.1.0
  anchored_overlay_engine:
    version: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^5.1.1
