/// Convenience exports for custom-mode wiring.
///
/// This keeps `package:headless_autocomplete/headless_autocomplete.dart` minimal,
/// while still allowing a single import for renderer contracts needed to wire
/// a custom theme/preset.
library;

export 'package:headless_contracts/headless_contracts.dart'
    show
        // autocomplete
        RAutocompleteSelectedValuesCommands,
        RAutocompleteSelectedValuesOverrides,
        RAutocompleteSelectedValuesPresentation,
        RAutocompleteSelectedValuesRenderRequest,
        RAutocompleteSelectedValuesRenderer,
        // dropdown
        RDropdownButtonRenderer,
        RDropdownButtonSlots,
        RDropdownButtonSpec,
        RDropdownButtonState,
        RDropdownCommands,
        RDropdownMenuMotionTokens,
        RDropdownMenuRenderRequest,
        RDropdownMenuTokens,
        RDropdownItemTokens,
        RDropdownOverrides,
        RDropdownRenderRequest,
        RDropdownResolvedTokens,
        RDropdownSemantics,
        RDropdownSize,
        RDropdownAnchorContext,
        RDropdownChevronContext,
        RDropdownItemContentContext,
        RDropdownItemContext,
        RDropdownMenuContext,
        RDropdownMenuSurfaceContext,
        RDropdownTriggerRenderRequest,
        RDropdownTriggerTokens,
        RDropdownTokenResolver,
        RDropdownVariant,
        ROverlayPhase,
        SafeDropdownChevronBuilder,
        SafeDropdownChevronContext,
        SafeDropdownEmptyStateBuilder,
        SafeDropdownEmptyStateContext,
        SafeDropdownItemBuilder,
        SafeDropdownItemContentBuilder,
        SafeDropdownItemContentContext,
        SafeDropdownItemContext,
        SafeDropdownMenuSurfaceBuilder,
        SafeDropdownMenuSurfaceContext,
        SafeDropdownRenderer,
        SafeDropdownTriggerBuilder,
        SafeDropdownTriggerContext,
        // textfield
        RTextFieldCommands,
        RTextFieldOverlayVisibilityMode,
        RTextFieldOverrides,
        RTextFieldRenderer,
        RTextFieldRenderRequest,
        RTextFieldResolvedTokens,
        RTextFieldSemantics,
        RTextFieldSlots,
        RTextFieldSpec,
        RTextFieldState,
        RTextFieldTokenResolver,
        RTextFieldVariant;
