name: headless_tokens
description: Headless tokens package (raw + semantic). Pure Dart.
version: 1.1.0
homepage: https://github.com/777genius/flutter_headless
repository: https://github.com/777genius/flutter_headless
issue_tracker: https://github.com/777genius/flutter_headless/issues

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  meta: ^1.11.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.0
